# Generated by Django 5.0.4 on 2024-04-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_teacher_f_link_teacher_l_link_teacher_t_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
